import "@/styles/globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

const inter = Inter({
    subsets: [ "latin" ],
    weight: [ "100", "200", "300", "400", "500", "600", "700", "800", "900" ]
})

export const metadata: Metadata = {
    title: "Markview",
    description: "Generated by create next app"
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body className={`bg-stone-950 text-white antialiased ${inter.className}`}>{children}</body>
        </html>
    )
}